name = "vbook-opds"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[vars]
# Mặc định người dùng có thể cấu hình GOOGLE_API_KEY công khai trên Worker
# hoặc cấu hình qua wrangler secret put GOOGLE_API_KEY
DEFAULT_PAGE_SIZE = "50"
